version: 2

jobs:
  # The build job
  build:
    working_directory: ~/hk-public-facilities-web
    docker:
      - image: circleci/node:14.0-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  # The test job
  test:
    working_directory: ~/hk-public-facilities-web
    docker:
      - image: circleci/node:14.0-browsers
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      # Lint the source code
      - run:
          name: Linting
          command: npm run lint
      # Test the source code
      - run:
          name: Testing
          command: npm test
      # End to End test
      - run:
          name: End to End Test
          command: npm run e2e
      - store_artifacts:
          path: ./reports/coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
        # filters:
        #   branches:
        #     only: master
